"""create company_members table

Revision ID: 3fb8a665517a
Revises: 80087cf6654a
Create Date: 2026-06-16 14:10:33.644910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb8a665517a'
down_revision: Union[str, Sequence[str], None] = '80087cf6654a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('Owner', 'Member', name='role'), nullable=False),
    sa.Column('status', sa.Enum('Pending_invite', 'Pending_request', 'Active', 'Rejected', name='invite_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_members')
    op.execute("DROP TYPE IF EXISTS role")
    op.execute("DROP TYPE IF EXISTS invite_status")
    # ### end Alembic commands ###
