"""create companies table

Revision ID: 80087cf6654a
Revises: cb10f2f67ee4
Create Date: 2026-06-15 14:52:20.142317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80087cf6654a'
down_revision: Union[str, Sequence[str], None] = 'cb10f2f67ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1500), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('visibility', sa.Enum('Hidden', 'Visible_to_all', name='company_visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("companies")
    sa.Enum(name="company_visibility").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
