"""change sname to lname into user model

Revision ID: cb10f2f67ee4
Revises: eeaad91efdb4
Create Date: 2026-06-12 18:32:04.724373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb10f2f67ee4'
down_revision: Union[str, Sequence[str], None] = 'eeaad91efdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lname', sa.String(length=50), nullable=True))
    op.drop_column('users', 'sname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'lname')
    # ### end Alembic commands ###
