"""BE-12: add company_id column to quiz_results table

Revision ID: e0d7a5aa2820
Revises: 7eeb6e23515d
Create Date: 2026-06-22 13:48:46.621927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d7a5aa2820'
down_revision: Union[str, Sequence[str], None] = '7eeb6e23515d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_results', sa.Column('company_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'quiz_results', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_results', type_='foreignkey')
    op.drop_column('quiz_results', 'company_id')
    # ### end Alembic commands ###
