"""make fname and sname nullable

Revision ID: eeaad91efdb4
Revises: 21b109b11669
Create Date: 2026-06-05 15:37:02.791348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeaad91efdb4'
down_revision: Union[str, Sequence[str], None] = '21b109b11669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'sname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'fname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
